name: Complex features of Github Actions Workflows
on: push
jobs:
  UseSecrets:
    runs-on: ubuntu-latest
    steps:
      - name: Get and use secrets 
        with:
          MY_SAVIOR: ${{ secrets.MY_SAVIOR }}
        env:
          MY_GOD: ${{ secrets.MY_GOD }}
        run: echo "My God is $MY_GOD and my Savior is also $MY_SAVIOR ."
