name: Complex features of Github Actions Workflows
on: push
jobs:
  UseSecrets:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          MY_SAVIOR: ${{ secrets.MY_SAVIOR }}
        run: |
          echo "$MY_SAVIOR"
