name: GitHub Actions Essential Features
on: push
jobs:
  CustomisedVariables:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: PostgresSQL Parameters
        run: echo "The postgres database name is $POSTGRES_DB and the user is $POSTGRES_USER"
        env:
          POSTGRES_DB: app_db
          POSTGRES_USER: admin
      - name: Setup python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: '3.10'
      - name: Execute a python script
        run: python hello.py